### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by codeyash** [yairEO/Do-in#1]
Please add one

**Comment by yairEO** [comment]
it's not missing, software is automatically licensed by the default law under the _Berne Convention_. 
Why does it matter anyway?

**Comment by codeyash** [comment]
It's not work that way
http://stackoverflow.com/questions/4007674/whats-the-default-license-of-code-published-at-github

Always create confusion.

I asked because I may use your code(may be not) but a clear license is always required before anyone can use it.

**Comment by yairEO** [comment]
Yeah use it why not, just don't make money for it directly or indirectly..I put it here so people would use it, like the rest of my stuff. If I wanted it not to be used, I would have used a private GIT repository

**Comment by codeyash** [comment]
:laughing:  don't make money out of code. Are we all students? Yes alone using and selling is evil.

Anyways I can't use yours and I got that. It's no good than keeping it private.(atleast for me)

**Comment by yairEO** [comment]
I'm sorry i don't really understand but it sounds like you will use it and you are happy? I guess.

**Comment by codeyash** [comment]
NO I will not use.

Unless 
You make it MIT or Apache or BSD or Public Domain... I mean clear license
